on: push
name: 🚀 Deploy website to Hostoo - via ftp
jobs:
  build:
    name: 🛠️ Build Process
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: 📂 Sync files
        uses: reisdev/portfolio@0.1.0
        with:
          server: ftp.reisdev.com.br
          username: ${{ secrets.HOSTOO_FTP_USER }}
          password: ${{ secrets.HOSTOO_FTP_PASSWORD }}
          dangerous-clean-slate: true
