on:
  push:
    branches:
      - main
name: 🚀 Deploy
jobs:
  deploy:
    name: 🛠️ Deploy to Hostoo
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: 🔨 Install and Build
        env:
          REACT_APP_GA_ID: ${{ secrets.REACT_APP_GA_ID }}
        run: |
          npm ci
          npm run build --if-present
      - name: 📂 Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.reisdev.com.br
          username: ${{ secrets.HOSTOO_FTP_USER }}
          password: ${{ secrets.HOSTOO_FTP_PASSWORD }}
          dangerous-clean-slate: true
          local-dir: ./build/
          server-dir: ./public_html/
